export * from './react'

export type IconType =
  | 'settings'
  | 'info'
  | 'arrowRight'
  | 'scan'
  | 'warning'
  | 'check'
  | 'copy'
  | 'connect'
  | 'passKey'
  | 'didit'
  | 'diditNameLogo'
  | 'close'
  | 'diditLogo'
  | 'idCard'
  | 'car'
  | 'passport'
  | 'closeCircle'
  | 'closeCircleBold'
  | 'checkCircle'
  | 'checkCircleBold'
  | 'refresh'
  | 'chevronLeft'
  | 'eye'
  | 'eyeSlash'
